title = "Hudba z FEKTu 2024"

[[votes_count]]
name = "Ostatní"
count = 1

[[votes_count]]
name = "VUT"
count = 2

[[votes_count]]
name = "FEKT"
count = 3

[[options]]
name = "Scorched Æarth"

[[options]]
name = "momentary francis"

[[options]]
name = "Levaross"

[[options]]
name = "ZBYNEK"

[[options]]
name = "July Morning"
